"""add indexes to schedulings table

Revision ID: 1eb1b7b3025a
Revises: 73684d6ad4a8
Create Date: 2026-08-17 22:19:52.755062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb1b7b3025a'
down_revision: Union[str, Sequence[str], None] = '73684d6ad4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_schedulings_client_id'), 'schedulings', ['client_id'], unique=False)
    op.create_index(op.f('ix_schedulings_end_time'), 'schedulings', ['end_time'], unique=False)
    op.create_index(op.f('ix_schedulings_service_id'), 'schedulings', ['service_id'], unique=False)
    op.create_index(op.f('ix_schedulings_start_time'), 'schedulings', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedulings_start_time'), table_name='schedulings')
    op.drop_index(op.f('ix_schedulings_service_id'), table_name='schedulings')
    op.drop_index(op.f('ix_schedulings_end_time'), table_name='schedulings')
    op.drop_index(op.f('ix_schedulings_client_id'), table_name='schedulings')
    # ### end Alembic commands ###
